### ISSUE TITLE
Thanks for sharing this :)

### ISSUE THREAD

**Issue by dharijanto** [hamidadelyar/fsm-chat#1]
Hi @hamidadelyar , I came across this repo through your blog post. Just wanna say thank you for the write up and clean code. I'm researching the most suitable backend arch for what I'm trying to build, and this definitely helps speeding up my research! :)

Hope you have a great one!

**Comment by hamidadelyar** [comment]
Hey @dharijanto, thanks very much for your message, glad to know it was useful to you :) All the best!
